name: "vpm-repos-gen action"
description: "Generate vpm package list."
author: "koyashiro"
branding:
  icon: "box"
  color: "blue"
inputs:
  version:
    description: "vpm-repos-gen version."
    required: false
    default: "latest"
  name:
    description: "`name` field of vpm package list."
    required: false
    default: ""
  id:
    description: "`id` field of vpm package list."
    required: false
    default: ""
  url:
    description: "`url` field of vpm package list."
    required: false
    default: ""
  author:
    description: "`author` field of vpm package list."
    required: false
    default: ""
  repos:
    description: "repositories for the package."
    required: false
    default: ""
  github_token:
    description: "GitHub API token."
    required: false
    default: ""
  output:
    description: "output path of vpm package list."
    required: true
    default: "repos.json"

runs:
  using: "composite"
  steps:
    - name: Install vpm-repos-gen
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: ${{ github.action_path }}/install.sh

    - name: Generate vpm package list
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        ID: ${{ inputs.id }}
        URL: ${{ inputs.url }}
        AUTHOR: ${{ inputs.author }}
        REPOS: ${{ inputs.repos }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OUTPUT: ${{ inputs.output }}
      run: ${{ github.action_path }}/generate.sh
