name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Test(latest)
        uses: ./
        with:
          output: "repos.json"

      - name: Test(v1.5.0)
        uses: ./
        with:
          version: "1.5.0"
          name: "koyashiro"
          id: "net.koyashiro.vpm"
          url: "https://vpm.koyashiro.net/repos.json"
          author: "koyashiro"
          repos: |
            koyashiro/udon-list
            koyashiro/udon-dictionary
            koyashiro/udon-json
          output: "-"

      - name: Test(v1.5.0)
        uses: ./
        with:
          version: "1.5.0"
          name: "koyashiro"
          id: "net.koyashiro.vpm"
          url: "https://vpm.koyashiro.net/repos.json"
          author: "koyashiro"
          repos: koyashiro/udon-list,koyashiro/udon-dictionary,koyashiro/udon-json
          output: "-"
