name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Test(latest)
        uses: ./
        with:
          output: "repos.json"

      - name: Test(v2.1.1)
        uses: ./
        with:
          version: "2.1.1"
          name: "koyashiro"
          id: "net.koyashiro.vpm"
          url: "https://vpm.koyashiro.net/repos.json"
          author: "koyashiro"
          repos: |
            koyashiro/udon-list
            koyashiro/udon-dictionary
            koyashiro/udon-json
          output: "-"

      - name: Test(v2.1.1)
        uses: ./
        with:
          version: "2.1.1"
          name: "koyashiro"
          id: "net.koyashiro.vpm"
          url: "https://vpm.koyashiro.net/repos.json"
          author: "koyashiro"
          repos: koyashiro/udon-list,koyashiro/udon-dictionary,koyashiro/udon-json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: "-"
